### ISSUE TITLE
Imports need to be relative

### ISSUE THREAD

**Issue by falkephi** [sankalpjonn/timeloop#2]
When installing timeloop with pip import fails because local imports are not specified the right way.

e.g. in the __init__.py

```python
from app import Timeloop
```

should be
```python
from .app import Timeloop
```

**Comment by sankalpjonn** [comment]
HI,

I have fixed the issue as part of a previous pending PR. Please check out version 1.0.2.

**Comment by falkephi** [comment]
Amazing! Thank you.

**Comment by sankalpjonn** [comment]
No problem. Am assuming this worked for you, so will close this issue. Please let me know if there are any more issues.

Thanks.
